### PR TITLE
Add feature show cores

### PR DESCRIPTION
**Pull request by TienTim**

### CODE REVIEW

**Comment by TienTim** [comment]
I still don't know exactly what the M1 Ultra's log return, because I don't have the machine. But it works on my M1. So you can test it.

**Comment by tlkh** [comment]
I do not have M1 Ultra also, but I think we can guess, haha

**Comment by iklier** [comment]
Here is a single sample of powermetrics from an M1 Ultra 64-core GPU system.
[M1_Ultra_64cGPU_powermetrics.txt](https://github.com/tlkh/asitop/files/8430619/M1_Ultra_64cGPU_powermetrics.txt)

**Comment by iklier** [comment]
Tried this PR on my M1 Ultra system and it crashes at:
`Traceback (most recent call last):
  File "/Users/ianklier/Library/Python/3.8/bin/asitop", line 8, in <module>
    sys.exit(main())
  File "/Users/ianklier/Library/Python/3.8/lib/python/site-packages/asitop/asitop.py", line 202, in main
    str(cpu_metrics_dict["E-Cluster" + str(i) + "_active"]),
KeyError: 'E-Cluster2_active'`

**Comment by iklier** [comment]
With 05cb05c:
```
Traceback (most recent call last):
  File "/Users/ianklier/Library/Python/3.8/bin/asitop", line 8, in <module>
    sys.exit(main())
  File "/Users/ianklier/Library/Python/3.8/lib/python/site-packages/asitop/asitop.py", line 200, in main
    e_core_gauges[i].title = "".join([
IndexError: list index out of range
```

**Comment by iklier** [comment]
eff1f86:
Regular invocation `sudo asitop` works.
Show Cores invocation `sudo asitop --show_cores SHOW_CORES` works.
asitop_show_cores_m1_ultra

**Comment by TienTim** [comment]
> [eff1f86](https://github.com/tlkh/asitop/commit/eff1f866fe75ee4fdbaea83480fb16b17899136a):
> Regular invocation `sudo asitop` works.
> Show Cores invocation `sudo asitop --show_cores SHOW_CORES` works.
> asitop_show_cores_m1_ultra

Thank you for testing it!

**Comment by tlkh** [comment]
Seems like it is working, so I'll merge it

**Pull request merged**
