### PR TITLE
Fix invalid parameter on powermetrics

### PR DESCRIPTION
**Pull request by paul-nameless**
I have an error running asitop, it tells that powermetrics got invalid parameter. I looked closer and find out that -u parameter should be passed instead of -o
```
> powermetrics --help | grep output
    -u | --output-file <file>    output to file [default: stdout]
```

I am running this on MacBook Air M1 and maybe you have different parameters so let me know if that's a valid fix.

### CODE REVIEW

**Comment by tlkh** [comment]
What version of macOS are you using?

I think that on Monterey (macOS 12.0), it is `-o`, but for previous OS it is `-u`.

Can you confirm you are not on Monterey? If that's the case, I think we should instead add a OS version check, and then substitute the correct argument name.

**Comment by paul-nameless** [comment]
Yes, I am on Big Sur 11.6 right now

**Comment by tlkh** [comment]
Feel free to see if you can come up with a OS version check, else, I’ll do it later this weekend.

**Comment by paul-nameless** [comment]
I think it should be working now, please have a look)

**Comment by paul-nameless** [comment]
I checked Big Sur, if you could check Monterey that would be great!

**Review by tlkh — APPROVED** [review]

**Comment by tlkh** [comment]
Thanks, all good!

**Pull request merged**
